name: Build Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw

      - name: Maven Test
        run: ./mvnw clean test

      - name: Generate JaCoCo Report
        run: ./mvnw jacoco:report

      - name: Upload JaCoCo Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Build with Maven (No tests)
        run: ./mvnw package -DskipTests
